#' @include zzz.R

# Main container class ---------------------------------------------------
#' The Shennong Class
#'
#' The Shennong object is the core data structure for bulk RNA-seq analysis in
#' the ShennongObject package. It extends the \code{\link[MultiAssayExperiment]{MultiAssayExperiment}}
#' class from Bioconductor, adding slots for common analysis components like
#' dimensional reductions, active assay/identity management, and project metadata.
#'
#' @slot organism Character string specifying the organism (e.g., "human").
#' @slot active_assay Character string indicating the name of the currently active
#'   assay within the \code{ExperimentList}.
#' @slot active_ident A factor representing the current identity (e.g., cluster
#'   or condition) for each sample in the object's primary \code{colData}.
#'   The length must match \code{nrow(colData(object))}.
#' @slot reductions A list storing dimensional reduction information (e.g., PCA,
#'   tSNE, UMAP). Typically, each element is a matrix where rows correspond to
#'   samples. It's recommended to store reductions associated with specific assays
#'   or the primary sample set.
#' @slot project_name Character string for the name of the project.
#' @slot misc A list for storing miscellaneous data associated with the object.
#' @slot version The version of the ShennongObject package used to create the object.
#' @slot commands A list to store analysis commands history (audit trail).
#' @slot tools A list to store results generated by various tools or functions.
#'
#' @inherit MultiAssayExperiment::MultiAssayExperiment details
#'
#' @name Shennong-class
#' @rdname Shennong-class
#' @aliases Shennong
#' @exportClass Shennong
#'
setClass("Shennong",
  contains = "MultiAssayExperiment",
  slots = c(
    organism = "character", # Organism name (e.g., "human")
    active_assay = "character", # Name of the active assay in ExperimentList
    active_ident = "factor", # Factor of sample identities (length = ncol object)
    reductions = "list", # List to store dim reductions (e.g., PCA, UMAP)
    project_name = "character", # Project name
    misc = "list", # List for miscellaneous data
    version = "character", # Package version when object was created
    commands = "list", # List for command history/log
    tools = "list" # List for tool-specific outputs
  )
)

# Command tracking class -------------------------------------------------
#' The ShennongCommand Class
#'
#' Used to log function calls, parameters, timestamps, and assay context
#' for tracking operations within a Shennong object
#'
#' @slot name Name of the command
#' @slot time_stamp POSIXct timestamp of command execution
#' @slot assay_used Name of assay used (or NA if not set)
#' @slot call_string Full function call string
#' @slot params List of parameters passed to the command
#'
#' @exportClass ShennongCommand
setClass(
  Class = "ShennongCommand",
  slots = c(
    name = "character",
    time_stamp = "POSIXct",
    assay_used = "character",
    call_string = "character",
    params = "ANY"
  ),
  prototype = list(assay_used = NA_character_)
)

# Dimensional reduction class --------------------------------------------
#' The ShennongReduction Class
#'
#' Stores dimensionality reduction results (e.g., PCA, UMAP, tSNE) for a
#' \code{Shennong} object. Inspired by Seurat's \code{DimReduc} structure,
#' this class contains embeddings, optional feature loadings, standard deviations,
#' a naming key, and metadata.
#'
#' @slot embedding A matrix of sample (cell) coordinates in reduced space.
#' @slot loadings A matrix of feature loadings (optional).
#' @slot stdev A numeric vector of standard deviations of each dimension.
#' @slot assay_used The name of the assay this reduction was computed from.
#' @slot global Logical. If TRUE, persists across assay removal.
#' @slot key A character prefix (e.g., "PC") prepended to column names of embedding matrix.
#' @slot misc A list of additional information.
#'
#' @exportClass ShennongReduction
setClass(
  Class = "ShennongReduction",
  slots = c(
    embedding = "matrix",
    loadings = "matrix",
    stdev = "numeric",
    assay_used = "character",
    global = "logical",
    key = "character",
    misc = "list"
  )
)

# Tools output class -----------------------------------------------------
#' The ShennongTool Class
#'
#' Stores the results generated by a computational tool or algorithm
#' (e.g., UCell, GSVA, AUCell) applied to data in a \code{Shennong} object.
#'
#' @slot method Character. The name of the tool or method used (e.g., "UCell").
#' @slot version Character. Version of the tool used.
#' @slot result A list or matrix storing the primary result.
#' @slot params A list of parameters used when running the tool.
#' @slot timestamp POSIXct. The time when the tool was run.
#' @slot status Character. Status of the run ("success", "error", etc.).
#' @slot citation Character. Optional reference or citation for the tool.
#' @slot misc A list of additional metadata.
#'
#' @exportClass ShennongTool
setClass(
  Class = "ShennongTool",
  slots = c(
    method = "character",
    version = "character",
    result = "list", # could also use "ANY" if not always list
    params = "list",
    timestamp = "POSIXct",
    status = "character",
    citation = "character",
    misc = "list"
  )
)
